steps:
  # Build image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/expense-tracker',
        '.'
      ]

  # Push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/expense-tracker'
      ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'expense-tracker',
        '--image',
        'gcr.io/$PROJECT_ID/expense-tracker',
        '--region',
        'asia-south1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/expense-tracker'

options:
  logging: CLOUD_LOGGING_ONLY